table Inventory
	lineageTag: fb1d0a30-2508-4058-b2cf-57a69e87200e

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: eefc9a3b-f74c-48f1-994e-1c3f87225b90
		summarizeBy: none
		sourceColumn: Date

		annotation UnderlyingDateTimeDataType = Date

	column WarehouseID
		dataType: int64
		formatString: #,0
		lineageTag: b5c9d6fe-98af-4c2e-a168-5ab4b1944a3a
		summarizeBy: none
		sourceColumn: WarehouseID

	column ProductID
		dataType: int64
		formatString: #,0
		lineageTag: a9f5d651-c6e0-4631-8681-eadc1ceecc0e
		summarizeBy: none
		sourceColumn: ProductID

	column OpeningUnits
		dataType: int64
		formatString: #,0
		lineageTag: 2cb76740-b3a4-4d82-9223-41c929fda490
		summarizeBy: none
		sourceColumn: OpeningUnits

	column ReceivedUnits
		dataType: int64
		formatString: #,0
		lineageTag: b623151b-c55d-435c-8147-70fd6d1dc122
		summarizeBy: none
		sourceColumn: ReceivedUnits

	column ShippedUnits
		dataType: int64
		formatString: #,0
		lineageTag: 0cf1fc37-42b1-4b65-8b6b-0b6b1e00e68c
		summarizeBy: none
		sourceColumn: ShippedUnits

	column StorageUnits
		dataType: int64
		formatString: #,0
		lineageTag: bfce836b-a7b6-45ee-a321-bb10f1155a9c
		summarizeBy: none
		sourceColumn: StorageUnits

	column WIPUnits
		dataType: int64
		formatString: #,0
		lineageTag: 02ea7706-490d-49ea-83aa-b763943a3333
		summarizeBy: none
		sourceColumn: WIPUnits

	column ClosingUnits
		dataType: int64
		formatString: #,0
		lineageTag: 2e3611d9-f70e-4a5e-9932-6fd7d09faa9d
		summarizeBy: none
		sourceColumn: ClosingUnits

	column ClosingValueUSD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: b729ef9b-b4a5-402d-9c94-7b0e8c8acfb0
		summarizeBy: none
		sourceColumn: ClosingValueUSD

	column DailyValueSumUSD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: 391bb613-c1b4-48a9-9406-596b995966c4
		summarizeBy: none
		sourceColumn: DailyValueSumUSD

	column CalendarDays
		dataType: int64
		formatString: #,0
		lineageTag: 409077e3-8836-40e3-ad21-8e1cb4c0fc99
		summarizeBy: none
		sourceColumn: CalendarDays

	column StockoutDays
		dataType: int64
		formatString: #,0
		lineageTag: c05eec38-b640-4581-89eb-5cec17bc4d66
		summarizeBy: none
		sourceColumn: StockoutDays

	column Age0to30USD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: ff3103e7-c9b1-448c-984b-24d77973182a
		summarizeBy: none
		sourceColumn: Age0to30USD

	column Age31to60USD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: bdfffe61-8303-43fb-a8ad-7590e87e6f39
		summarizeBy: none
		sourceColumn: Age31to60USD

	column Age61to90USD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: e2366463-2985-49a5-a14f-daae36aa4c45
		summarizeBy: none
		sourceColumn: Age61to90USD

	column Age91to180USD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: cd984a0a-08a7-4725-a624-7ecbc31bbb41
		summarizeBy: none
		sourceColumn: Age91to180USD

	column AgeOver180USD
		dataType: decimal
		formatString: $#,0.00
		lineageTag: 5899117d-e213-4c72-b94b-b8d0623e2555
		summarizeBy: none
		sourceColumn: AgeOver180USD

	partition Inventory = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataFolder & "Inventory.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers, "", null, Replacer.ReplaceValue, Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls, {{"Date", type date}, {"WarehouseID", Int64.Type}, {"ProductID", Int64.Type}, {"OpeningUnits", Int64.Type}, {"ReceivedUnits", Int64.Type}, {"ShippedUnits", Int64.Type}, {"StorageUnits", Int64.Type}, {"WIPUnits", Int64.Type}, {"ClosingUnits", Int64.Type}, {"ClosingValueUSD", Currency.Type}, {"DailyValueSumUSD", Currency.Type}, {"CalendarDays", Int64.Type}, {"StockoutDays", Int64.Type}, {"Age0to30USD", Currency.Type}, {"Age31to60USD", Currency.Type}, {"Age61to90USD", Currency.Type}, {"Age91to180USD", Currency.Type}, {"AgeOver180USD", Currency.Type}}, "en-US")
				in Typed

